### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by h9k**

### CODE REVIEW

**Comment by h9k** [comment]
The Travis CI check does not start for some reason... maybe I should close the pull request and create a new one again?

**Comment by papakai** [comment]
close+reopen doesn't help imo, I expect things to get triggered just by commit.

**Comment by papakai** [comment]
I suggest to copy'n'paste the .gitignore file from whmcs-ispapi-registrar. Use that as new commit then :-)

**Comment by papakai** [comment]
Even though the checks are failing, I merge this PR. the checks are just bringing up code validation issues in direction of PSR1 and PSR2 standard. Working on them can be handled at the time when you merge the module versions to a final module code base.

**Pull request merged**
